### ISSUE TITLE
Specs are failing

### ISSUE THREAD

**Issue by CucumisSativus** [spree-contrib/spree_email_to_friend#64]
Spec are failing because of lack of proper `mails_from` preference.

A comprehensive list of steps to reproduce the issue.
1. install all dependencies
2. bun `bundle exec rspec spec`

What you're expecting to happen 
I'm expecting all specs to pass

What's actually happening.
```
 107 LOC (51.4%) covered.
/Users/michal/.rvm/gems/ruby-2.2.2@spree_email/bundler/gems/spree-5f439e405e97/core/app/models/spree/preferences/preferable.rb:62:in `has_preference!': mails_from preference not defined (NoMethodError)
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/bundler/gems/spree-5f439e405e97/core/app/models/spree/preferences/preferable.rb:42:in `get_preference'
	from /Users/michal/spree_email_to_friend/app/mailers/spree/to_friend_mailer.rb:2:in `<class:ToFriendMailer>'
	from /Users/michal/spree_email_to_friend/app/mailers/spree/to_friend_mailer.rb:1:in `<top (required)>'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/michal/spree_email_to_friend/spec/mailers/to_friend_mailer_spec.rb:1:in `<top (required)>'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/bin/rspec:23:in `load'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/bin/rspec:23:in `<main>'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michal/.rvm/gems/ruby-2.2.2@spree_email/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by futhr** [comment]
Hi @CucumisSativus all specs happy now thanks in `master` branch.
